# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '我的网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.1'

  # Pods for 我的网易新闻

  target '我的网易新闻Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '我的网易新闻UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
